// Generated by gencpp from file XP/ViSlam.msg
// DO NOT EDIT!


#ifndef XP_MESSAGE_VISLAM_H
#define XP_MESSAGE_VISLAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace XP
{
template <class ContainerAllocator>
struct ViSlam_
{
  typedef ViSlam_<ContainerAllocator> Type;

  ViSlam_()
    : pose_stamped()
    , anchor_stamp()  {
    }
  ViSlam_(const ContainerAllocator& _alloc)
    : pose_stamped(_alloc)
    , anchor_stamp()  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_stamped_type;
  _pose_stamped_type pose_stamped;

   typedef ros::Time _anchor_stamp_type;
  _anchor_stamp_type anchor_stamp;





  typedef boost::shared_ptr< ::XP::ViSlam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::XP::ViSlam_<ContainerAllocator> const> ConstPtr;

}; // struct ViSlam_

typedef ::XP::ViSlam_<std::allocator<void> > ViSlam;

typedef boost::shared_ptr< ::XP::ViSlam > ViSlamPtr;
typedef boost::shared_ptr< ::XP::ViSlam const> ViSlamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::XP::ViSlam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::XP::ViSlam_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace XP

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'XP': ['/home/hangm/baidu_git/tracking/XP/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::XP::ViSlam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::XP::ViSlam_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::XP::ViSlam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::XP::ViSlam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::XP::ViSlam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::XP::ViSlam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::XP::ViSlam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0417395a4435c0aef7bd19253e5ff64";
  }

  static const char* value(const ::XP::ViSlam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0417395a4435c0aULL;
  static const uint64_t static_value2 = 0xef7bd19253e5ff64ULL;
};

template<class ContainerAllocator>
struct DataType< ::XP::ViSlam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "XP/ViSlam";
  }

  static const char* value(const ::XP::ViSlam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::XP::ViSlam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped pose_stamped\n\
time anchor_stamp\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::XP::ViSlam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::XP::ViSlam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_stamped);
      stream.next(m.anchor_stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ViSlam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::XP::ViSlam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::XP::ViSlam_<ContainerAllocator>& v)
  {
    s << indent << "pose_stamped: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_stamped);
    s << indent << "anchor_stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.anchor_stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XP_MESSAGE_VISLAM_H
